version: '3.9'

services:
  postgresql:
    image: postgres
    build: ./database.Dockerfile
    restart: always
    ports:
      - '5432:5432'
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: aquelasenha123